# Generated by Django 4.2.1 on 2023-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
